cmake \
-D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX=/usr/local \

-D INSTALL_C_EXAMPLES=OFF \
-D INSTALL_PYTHON_EXAMPLES=OFF \

-D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules/ \
-D BUILD_EXAMPLES=OFF \

-D WITH_XINE=ON \
-D WITH_QT=ON \

-D BUILD_PYTHON_SUPPORT=ON \
-D BUILD_NEW_PYTHON_SUPPORT=ON \

-D WITH_V4L=ON \
-D ENABLE_AVX=ON \

-D WITH_OPENGL=ON \
-D WITH_OPENCL=ON \

-D WITH_IPP=ON \
-D WITH_TBB=ON \
-D WITH_EIGEN=ON \
-D WITH_V4L=ON \

-D BUILD_TESTS=OFF \
-D BUILD_PERF_TESTS=OFF \

-D WITH_CUDA=OFF \

-D CMAKE_INSTALL_PREFIX=~/.opencv-3.1.0 \
-E \
..
